const listaPalabras = [
  // "cabra",
  "Animal",
  "ornitorrinco",
  // "Animal",
  "elefante",
  // "Animal",
  "alcaravan",
  // "Animal",
  "cercopiteco de brazza",
  // "Animal",
  "cucaracha",
  //"Animal",
  "simio",
  "Animal",
  // "teclado",
  "Periférico de PC",
  // "raton",
  "Periférico de PC",
  // "impresora",
  "Periférico de PC",
  // "altavoces",
  "Periférico de PC",
  //"fuente de alimentacion",
  "Componente de PC",
  //"triciclo",
  "Vehículo",
  //"motonieve",
  "Vehículo",
  // "buggy",
  // "Vehículo",
  "avion",
  "Vehículo",
  "locomotora",
  "Vehículo",
  "patera",
  "Vehículo",
  "java",
  "Lenguaje de programación",
  "javascript",
  "Lenguaje de programación",
  "gigabyte",
  "Unidad de almacenamiento",
  "iron man",
  "Y yo soy...",
  "equilibrado",
  "Perfectamente...",
  "guns n' roses",
  "Banda de Rock",
  "slash",
  "Guitarrista / Símbolo",
  "poker",
  "Juego de cartas",
  "xiaomi",
  "Marca de móviles",
  "coca cola",
  "Refresco",
  "erp",
  "Software gestión empresas",
  "instrucciones",
  "Guía sobre algo",
  "creditos",
  "Final de una pelicula",
  "microfono",
  "Para capturar audio",
  "lawrence de arabia",
  "Película",
  "star wars",
  "Saga de películas",
  "El Señor de Los Anillos",
  "Saga de Películas",
  "Transformers",
  "Saga de Películas",
  "Salvar al Soldado Ryan",
  "Película",
  "El bueno, el feo y el malo",
  "Película",
  "AC/DC",
  "Banda de Rock",
  "Kiss",
  "Banda de Rock",
  "Metallica",
  "Banda de Rock",
  "Led Zepellin",
  "Banda de Rock",
  "Bohemian Rhapsody",
  "Canción Queen",
  "Bruce Springsteen",
  "Cantante",
  "Armin Van Buuren",
  "DJ",
  "Brian Cross",
  "DJ",
  "Supercalifragilisticoexpialidoso",
  "Canción célebre",
  "American dad",
  "Serie",
  "Family Guy",
  "Serie",
  "Breaking Bad",
  "Serie",
  "Chicho Terremoto",
  "Serie de dibujos",
  "Friends",
  "ALF",
  "Serie",
];
